### ISSUE TITLE
Set-up github actions environments 

### ISSUE THREAD

**Issue by mariannovotny** [G-Research/siembol#47]
We would like to ensure integrity of CI/CD pipeline during publishing artifacts into central maven and docker hub. Try to use GHAE https://docs.github.com/en/actions/reference/environments and prepare protection rules with

- deployment branches
- review workflow
- storing secrets

**Comment by jgiannuzzi** [comment]
I looked further into using GitHub Actions Environments for our CI/CD pipeline and I think it will require a few changes to the way it currently works. _Of course_, it wasn't as simple to enable as I thought it would 🙄

This is because of the following GHAE constraints:
* The workflow review feature does not use `CODEOWNERS` but a separate list of people, and a PR author can approve their own workflow run
  ➡️ we should thus not use the workflow review feature, but instead rely on the existing branch protection on `master`
* Access to an environment can be restricted to a (list of) specific branch(es)
  ➡️ we should use this to restrict access to the environment to the `master` branch only
* A workflow running for a `release` event will be considered as running for the tag, and not the branch
  ➡️ as anyone with write access to the repo can create and delete tags/releases, we can't use a pattern like `v*` to restrict the 'branches' that can access the environment (GitHub considers tag names as being branch names in this case — which also means that anyone with write access could create a branch starting with `v` — i.e. `vhatever` — and access the secrets)
* The same applies to a tag `push` event
* Using environment secrets is done at the job level, not at the step level
  ➡️ if our jobs that build and push Docker images reference an environment, they will fail for branches/tags that don't have access to it

I suggest changing our CI/CD and release process as follows to take advantage of GHAE and ensure that only reviewed commits can produce released artifacts:
* Split the Docker image jobs between build and push. Build jobs will run for any branch (even in forks) and output the image as a tarball uploaded as a workflow artifact. Push jobs will only run for the `master` branch of the upstream repo and will reference the environment (so they can push to Docker Hub).
* The Maven Central release job will only run for the `master` branch of the upstream repo and will reference the environment (so it can sign the packages and push them to Maven Central). When a non-`SNAPSHOT` version is detected, it will automatically create a tag (and possibly even a release). It will then increment the version in all `pom.xml` files and add `-SNAPSHOT`, then push that commit to `master` (note: this might not be possible without a bot and might instead require to create a PR that should be approved and merged manually). The goal here is to _not_ use tags — as anyone can write them — but to still make sure we don't overwrite previous releases.

Comments welcome! Especially @EnricoMi as you helped setup the current CI/CD pipeline 😎

**Comment by EnricoMi** [comment]
>     * Push jobs will only run for the `master` branch of the upstream repo

Push jobs also run on the `master` branch of the fork, and fail there, because no secrets are defined. This is annoying for fork repos. Hence, those jobs should also only run when the repo name is `g-research/siembol`.

**Comment by jgiannuzzi** [comment]
> > ```
> > * Push jobs will only run for the `master` branch of the upstream repo
> > ```
> 
> 
> Push jobs also run on the `master` branch of the fork, and fail there, because no secrets are defined. This is annoying for fork repos. Hence, those jobs should also only run when the repo name is `g-research/siembol`.

Good point, @EnricoMi! I will update my PR to fix that.

**Comment by EnricoMi** [comment]
Did you consider moving the `release*` jobs into a separate workflow that runs on `workflow_run` event and have it triggered from the CI workflow? Then it is guaranteed to run in the g-research repo context as well.

**Comment by jgiannuzzi** [comment]
I have added `!github.event.repository.fork` to the condition to make sure it only runs on this repo.

**Comment by jgiannuzzi** [comment]
> Did you consider moving the `release*` jobs into a separate workflow that runs on `workflow_run` event and have it triggered from the CI workflow? Then it is guaranteed to run in the g-research repo context as well. You can still use the environment feature there I think.

I very briefly looked into it but I didn't really see the added value compared to this approach. Do you think there would be advantages to doing it that way?

**Comment by EnricoMi** [comment]
That approach would more strictly follow separation of concern. The CI workflow builds and tests the code, in our repo and in forks. We would never deploy from a fork. When CI workflow succeeded and did not run on a fork, then we run the CD workflow and eventually release. But besides moving the release code out of a workflow that may run on a fork, there is no extra value in this approach. Just an alternative (and better visible separation).

**Comment by jgiannuzzi** [comment]
I spent some time thinking about your idea, @EnricoMi, and I really like it. One great advantage I see is that it I think it would allow us to do artifact deployment when a tag gets pushed. The `workflow_run` pipeline would start by checking that it's a tag that was made from a commit belonging to a protected branch (with something like `git branch --contains $tag` + API call to GH to check the branch protection settings).

With regards to accessing the artifacts of the CI workflow, have a look at my simplification suggestion [here](https://github.com/G-Research/siembol/pull/69#discussion_r638618884). This could easily be adapted to a for loop.

**Comment by EnricoMi** [comment]
Yes, `workflow_run` workflows are nice because they allow to event-based chain workflow runs: one triggers the other one. You can check the circumstance at the beginning of the triggered run and go from there. And you implement your workflow once for your repo context, which then can be triggered by in-repo or fork-repo context workflows.
